[build]
command = "npm run build"
publish = "_site"

[build.processing]
skip_processing = true

[build.environment]
NODE_VERSION = "node"

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1"

[[redirects]]
from = "https://cheery-flan-2e1be4.netlify.app/*"
to = "https://stateparks.troyv.dev/:splat"
status = 301
force = true
